### ISSUE TITLE
Implement the email Utility.

### ISSUE THREAD

**Issue by chandur626** [chandur626/TeachersPetBot#2]
Email would be another important source of communication that can be established through discord. Implement the email utility which acts as a wrapper to send emails of plain messages and attachments.

**Comment by SriPallaviDamuluri** [comment]
looks good

**Comment by nirajlavani** [comment]
Would automated emails be sent by one account/person (like a specific instructor) or multiple accounts?

**Comment by chandur626** [comment]
Automated emails can be initiated by multiple accounts.

**Comment by HariniBharata** [comment]
Can we send multiple emails at once?

**Comment by 05sandesh** [comment]
Hey, can we send multiple attachments in the same mail?

**Comment by chandur626** [comment]
> Can we send multiple emails at once?

Yeah there is a provision to provide a list recipients to send same email to multiple users.

**Comment by chandur626** [comment]
> Hey, can we send multiple attachments in the same mail?

Yeah even attachment is accepted as a list where multiple attachments can be provided at the same time.
