### ISSUE TITLE
Send emails on reminder 

### ISSUE THREAD

**Issue by chandur626** [chandur626/TeachersPetBot#3]
Implement the functionality of sending emails to users to remind them of an event or deadline.

**Comment by nirajlavani** [comment]
Where are we getting the test recipient email variable?

**Comment by 05sandesh** [comment]
Hi @chandur626, does the "check_reminders_due_today" function handles all the functionalities we discussed

**Comment by chandur626** [comment]
> Where are we getting the test recipient email variable?

There is a repository secret in the repo settings defined for the same.

**Comment by chandur626** [comment]
> Hi @chandur626, does the "check_reminders_due_today" function handles all the functionalities we discussed

Yeah as discussed it handles all the assignments including projects which are due in a day.
