### ISSUE TITLE
email address specification

### ISSUE THREAD

**Issue by chandur626** [chandur626/TeachersPetBot#9]
Implement the logic to store, update and delete the email address of specific users. Email addresses are needed to send reminders and attachments to users via email.

**Comment by SriPallaviDamuluri** [comment]
are we really deleting the email records from the db?

**Comment by nirajlavani** [comment]
What's the significance of the is_active column in email_address table?

**Comment by chandur626** [comment]
> What's the significance of the is_active column in email_address table?

It indicates whether that particular record in the table is active or not.

**Comment by chandur626** [comment]
> are we really deleting the email records from the db?

We are maintaining a column is_active for the same. In the case of delete, the is_active is set to false.
